name: Docker Compose CI and Azure Web App Deployment

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x' # Especifica a versão do .NET SDK

      - name: Restore dependencies
        run: dotnet restore ./FCG.sln

      - name: Build solution
        run: dotnet build ./FCG.sln --configuration Release --no-restore

      - name: Run tests
        run: dotnet test ./tests/FCG.Service.Tests/FCG.Service.Tests.csproj --configuration Release --no-build --no-restore --verbosity normal 

  docker-build-and-push:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push with Docker Compose
        run: |
          docker compose build
          docker compose push

  deploy-to-azure:
    runs-on: ubuntu-latest
    needs: docker-build-and-push

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'webContainerAppFGC'
          slot-name: 'Production'
          publish-profile: ${{ secrets.PUBLISH_PROFILE }}
          images: 'dtpontes/fcgpresentation:latest'
          
       # Log in to Azure
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}      

      # Restart the Azure Web App (ADD THIS AFTER THE DEPLOY STEP)
      - name: Restart Azure Web App
        uses: azure/cli@v2
        with:
          inlineScript: az webapp restart --name webContainerAppFGC --resource-group RGDockFiap
