name: Docker Compose CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-with-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # Good practice for more advanced Docker features

      # If you need to log in to a Docker registry (e.g., for pulling base images or pushing)
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Log in to GitHub Container Registry
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.SECRET_GITHUB_TOKEN }}

      - name: Build services with Docker Compose
        run: docker-compose -f docker-compose.yml build

      # Example: Run services in detached mode (e.g., for integration tests)
      # - name: Start services
      #   run: docker-compose -f docker-compose.yml up -d

      # Example: Run tests on a specific service
      # - name: Run tests
      #   run: docker-compose -f docker-compose.yml run --rm fcg.presentation your_test_command

      # Example: Stop services
      # - name: Stop services
      #   if: always() # Ensure services are stopped even if previous steps fail
      #   run: docker-compose -f docker-compose.yml down
