name: Docker Compose CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-with-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Step1
        uses: actions/checkout@v4

      - name: Step2
        run: echo "Esse é o step 2"

     
