name: Docker Compose CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-with-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Step1
        uses: actions/checkout@v4

      - name: Step2
        uses: echo "Esse é o step 2"

     
